image: docker:stable

before_script:
- docker info

variables:
  GIT_SSL_NO_VERIFY: "true"

build-master:
  stage: build
  script:
    - docker build --pull -t "$REGISTRY_HOST/$CI_PROJECT_NAME" .
    - docker push "$REGISTRY_HOST/$CI_PROJECT_NAME"
  only:
    - master
  tags:
    - docker-bot

build:
  stage: build
  script:
    - docker build --pull -t "$REGISTRY_HOST/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$REGISTRY_HOST/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - docker-bot
