image: docker:stable

before_script:
- docker info

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME" .
    - docker push "$CI_REGISTRY_HOST/$CI_PROJECT_NAME"
  only:
    - master
  tags:
    - docker-bot

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_HOST/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - docker-bot
